---
- import_playbook: ../static-assignments/common.yml

- hosts: all
  name: Include dynamic variables

  tasks:
    - include_vars:
        file: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- import_playbook: ../static-assignments/uat-webservers.yml
